{{- if .Values.broker.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "artemis.fullname" . }}-credentials
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: {{ .Values.broker.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.broker.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.broker.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "artemis.fullname" . }}-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: {{ .Values.broker.externalSecrets.remoteRefs.adminPassword }}
    {{- if .Values.broker.tls.enabled }}
    - secretKey: tls-keystore-password
      remoteRef:
        key: {{ .Values.broker.externalSecrets.remoteRefs.tlsKeystorePassword }}
    - secretKey: tls-truststore-password
      remoteRef:
        key: {{ .Values.broker.externalSecrets.remoteRefs.tlsTruststorePassword }}
    {{- end }}
{{- end }}
