{{- if and (not .Values.broker.auth.existingSecret) (not .Values.broker.externalSecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artemis.fullname" . }}-credentials
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
data:
  admin-password: {{ default (randAlphaNum 24) .Values.broker.auth.adminPassword | b64enc | quote }}
  {{- if .Values.broker.tls.enabled }}
  tls-keystore-password: {{ randAlphaNum 24 | b64enc | quote }}
  tls-truststore-password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}
