apiVersion: v1
kind: Service
metadata:
  name: {{ include "artemis.fullname" . }}-live-headless
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
    role: live
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "artemis.selectorLabels" . | nindent 4 }}
    role: live
  ports:
    - name: openwire
      port: {{ .Values.ports.openwire }}
      targetPort: openwire
      protocol: TCP
    {{- if .Values.broker.clustered }}
    - name: cluster
      port: {{ .Values.ports.cluster }}
      targetPort: cluster
      protocol: TCP
    {{- end }}
    {{- if .Values.broker.ha.enabled }}
    - name: replication
      port: {{ .Values.ports.replication }}
      targetPort: replication
      protocol: TCP
    {{- end }}
    {{- if .Values.monitoring.jmxExporter.enabled }}
    - name: metrics
      port: {{ .Values.monitoring.jmxExporter.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
---
{{- if .Values.broker.ha.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "artemis.fullname" . }}-backup-headless
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
    role: backup
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "artemis.selectorLabels" . | nindent 4 }}
    role: backup
  ports:
    - name: openwire
      port: {{ .Values.ports.openwire }}
      targetPort: openwire
      protocol: TCP
    {{- if .Values.broker.ha.enabled }}
    - name: replication
      port: {{ .Values.ports.replication }}
      targetPort: replication
      protocol: TCP
    {{- end }}
    {{- if .Values.monitoring.jmxExporter.enabled }}
    - name: metrics
      port: {{ .Values.monitoring.jmxExporter.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
{{- end }}
